
[modaction_invocations]
display_location          = event_menu
fields                    = orig_sid,orig_rid
label                     = View Adaptive Response Invocations
link.method               = get
link.target               = blank
link.uri                  = /app/Splunk_SA_CIM/modaction_workflow?action=invocations&sid=$orig_sid$&rid=$orig_rid$&source_sid=$@sid$&namespace=$@namespace$
type                      = link

[modaction_results]
display_location          = event_menu
fields                    = orig_sid,orig_rid
label                     = View Adaptive Response Results
link.method               = get
link.target               = blank
link.uri                  = /app/Splunk_SA_CIM/modaction_workflow?action=results&sid=$orig_sid$&rid=$orig_rid$&source_sid=$@sid$&namespace=$@namespace$
type                      = link
